version: '3.7'

services:
  banker:
    container_name: banker
    working_dir: /var/www/html
    image: node:14-alpine
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    ports:
      - 3000:3000
    command: npm run start:dev
    links:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis:/bitnami/redis/data

volumes:
  mysql:
    driver: local
  redis:
    driver: local
